# Complete Exercise Encyclopedia - All exercises from the Excel file
EXERCISES_DATA = [
    # ==================== ESPALDA ====================
    {"muscle": "Espalda", "name": "Pull-up", "exercise_type": "Tirón vertical", "pattern": "Peso corporal", "equipment": "Barra fija/anillas", "subtype": "Prono, ancho, medio, estrecho; sin lastre"},
    {"muscle": "Espalda", "name": "Weighted pull-up", "exercise_type": "Tirón vertical", "pattern": "Peso corporal + lastre", "equipment": "Cinturón, chaleco", "subtype": "Igual que pull-up con peso adicional"},
    {"muscle": "Espalda", "name": "Chin-up", "exercise_type": "Tirón vertical", "pattern": "Peso corporal", "equipment": "Barra fija", "subtype": "Supino, ancho/estrecho"},
    {"muscle": "Espalda", "name": "Neutral-grip pull-up", "exercise_type": "Tirón vertical", "pattern": "Peso corporal", "equipment": "Barra agarre neutro", "subtype": "Palmas enfrentadas"},
    {"muscle": "Espalda", "name": "Archer pull-up", "exercise_type": "Tirón vertical", "pattern": "Peso corporal", "equipment": "Barra fija", "subtype": "Un brazo domina; variante avanzada"},
    {"muscle": "Espalda", "name": "Typewriter pull-up", "exercise_type": "Tirón vertical", "pattern": "Peso corporal", "equipment": "Barra fija", "subtype": "Desplazando el cuerpo lateralmente arriba"},
    {"muscle": "Espalda", "name": "L-sit pull-up", "exercise_type": "Tirón vertical", "pattern": "Peso corporal", "equipment": "Barra fija/anillas", "subtype": "Piernas extendidas en L"},
    {"muscle": "Espalda", "name": "Muscle-up", "exercise_type": "Tirón vertical + empuje", "pattern": "Peso corporal", "equipment": "Barra/anillas", "subtype": "Combina dominada y fondo, muy avanzado"},
    {"muscle": "Espalda", "name": "Assisted pull-up", "exercise_type": "Tirón vertical", "pattern": "Máquina", "equipment": "Assisted pull-up machine", "subtype": "Contrapeso reduce carga"},
    {"muscle": "Espalda", "name": "Inverted row / Australian pull-up", "exercise_type": "Tirón horizontal", "pattern": "Peso corporal", "equipment": "Barra baja/TRX/anillas", "subtype": "Cuerpo alineado, pies en suelo"},
    {"muscle": "Espalda", "name": "Feet-elevated inverted row", "exercise_type": "Tirón horizontal", "pattern": "Peso corporal", "equipment": "Barra baja/TRX", "subtype": "Mayor carga al elevar pies"},
    {"muscle": "Espalda", "name": "One-arm inverted row", "exercise_type": "Tirón horizontal", "pattern": "Peso corporal", "equipment": "Barra/TRX/anillas", "subtype": "Unilateral, muy demandante"},
    {"muscle": "Espalda", "name": "Superman", "exercise_type": "Extensión columna", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Extensión simultánea brazos/piernas"},
    {"muscle": "Espalda", "name": "Back extension suelo", "exercise_type": "Extensión columna", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Sólo tronco, rango corto"},
    {"muscle": "Espalda", "name": "Reverse snow angel", "exercise_type": "Extensión/posterior", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Abd, rotación y abducción de brazos"},
    {"muscle": "Espalda", "name": "Bird dog", "exercise_type": "Estabilidad lumbar", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Contralateral brazo/pierna"},
    {"muscle": "Espalda", "name": "Barbell bent-over row", "exercise_type": "Tirón horizontal", "pattern": "Barra", "equipment": "Libre", "subtype": "Tronco inclinado, agarre prono"},
    {"muscle": "Espalda", "name": "Barbell row underhand", "exercise_type": "Tirón horizontal", "pattern": "Barra", "equipment": "Libre", "subtype": "Agarres supino (más bíceps)"},
    {"muscle": "Espalda", "name": "Close-grip barbell row", "exercise_type": "Tirón horizontal", "pattern": "Barra", "equipment": "Libre", "subtype": "Manos cercanas, más dorsales medios"},
    {"muscle": "Espalda", "name": "Pendlay row", "exercise_type": "Tirón horizontal", "pattern": "Barra", "equipment": "Libre", "subtype": "Desde el suelo, torso paralelo"},
    {"muscle": "Espalda", "name": "Yates row", "exercise_type": "Tirón horizontal", "pattern": "Barra", "equipment": "Libre", "subtype": "Tronco menos inclinado, agarre supino"},
    {"muscle": "Espalda", "name": "Landmine row", "exercise_type": "Tirón horizontal", "pattern": "Barra + soporte", "equipment": "Landmine", "subtype": "Barra anclada en esquina"},
    {"muscle": "Espalda", "name": "T-bar row", "exercise_type": "Tirón horizontal", "pattern": "Barra T-bar", "equipment": "casero", "subtype": "V-handle en barra apoyada"},
    {"muscle": "Espalda", "name": "Deadlift convencional", "exercise_type": "Bisagra", "pattern": "Barra", "equipment": "Libre", "subtype": "Dorsales, erectores, trapecio"},
    {"muscle": "Espalda", "name": "Sumo deadlift", "exercise_type": "Bisagra", "pattern": "Barra", "equipment": "Libre", "subtype": "Base amplia, más aductores/glúteo"},
    {"muscle": "Espalda", "name": "Romanian deadlift", "exercise_type": "Bisagra", "pattern": "Barra", "equipment": "Libre", "subtype": "Foco isquios/glúteo y erectores"},
    {"muscle": "Espalda", "name": "Stiff-leg deadlift", "exercise_type": "Bisagra", "pattern": "Barra", "equipment": "Libre", "subtype": "Piernas casi rectas, más isquios"},
    {"muscle": "Espalda", "name": "Snatch-grip deadlift", "exercise_type": "Bisagra", "pattern": "Barra", "equipment": "Libre", "subtype": "Agarre muy ancho, gran espalda alta"},
    {"muscle": "Espalda", "name": "Barbell shrug", "exercise_type": "Elevación escapular", "pattern": "Barra", "equipment": "Libre", "subtype": "Trapecio superior"},
    {"muscle": "Espalda", "name": "One-arm dumbbell row", "exercise_type": "Tirón horizontal", "pattern": "Mancuerna", "equipment": "Banco", "subtype": "Clásico en banco con apoyo"},
    {"muscle": "Espalda", "name": "Dumbbell bent-over row", "exercise_type": "Tirón horizontal", "pattern": "Mancuerna", "equipment": "Libre", "subtype": "Bilateral, torso inclinado"},
    {"muscle": "Espalda", "name": "Chest-supported DB row", "exercise_type": "Tirón horizontal", "pattern": "Mancuerna", "equipment": "Banco inclinado", "subtype": "Pecho apoyado, menos trampa"},
    {"muscle": "Espalda", "name": "Kroc row", "exercise_type": "Tirón horizontal", "pattern": "Mancuerna", "equipment": "Banco", "subtype": "Muy pesado, altas repeticiones"},
    {"muscle": "Espalda", "name": "Dumbbell pullover", "exercise_type": "Tirón vertical", "pattern": "Mancuerna", "equipment": "Banco", "subtype": "Dorsal + pectoral"},
    {"muscle": "Espalda", "name": "Renegade row", "exercise_type": "Tirón + core", "pattern": "Mancuerna", "equipment": "Suelo", "subtype": "Plancha con remo alterno"},
    {"muscle": "Espalda", "name": "DB reverse fly", "exercise_type": "Abducción horizontal", "pattern": "Mancuerna", "equipment": "Banco inclinado/de pie", "subtype": "Más deltoide posterior/romboides"},
    {"muscle": "Espalda", "name": "KB bent-over row", "exercise_type": "Tirón horizontal", "pattern": "Kettlebell", "equipment": "Libre", "subtype": "Similar a DB row"},
    {"muscle": "Espalda", "name": "KB renegade row", "exercise_type": "Tirón + core", "pattern": "Kettlebell", "equipment": "Suelo", "subtype": "Variante con KB"},
    {"muscle": "Espalda", "name": "KB swing", "exercise_type": "Bisagra", "pattern": "Kettlebell", "equipment": "Libre", "subtype": "Cadena posterior (incluye espalda)"},
    {"muscle": "Espalda", "name": "Lat pulldown wide grip", "exercise_type": "Tirón vertical", "pattern": "Polea", "equipment": "Lat machine", "subtype": "Agarres ancho, prono"},
    {"muscle": "Espalda", "name": "Lat pulldown close/neutral", "exercise_type": "Tirón vertical", "pattern": "Polea", "equipment": "Lat machine", "subtype": "Barra V/neutral"},
    {"muscle": "Espalda", "name": "Underhand pulldown", "exercise_type": "Tirón vertical", "pattern": "Polea", "equipment": "Lat machine", "subtype": "Supino, más bíceps"},
    {"muscle": "Espalda", "name": "Straight-arm pulldown", "exercise_type": "Tirón vertical", "pattern": "Polea", "equipment": "Polea alta", "subtype": "Codo casi fijo, aíslas dorsal"},
    {"muscle": "Espalda", "name": "Cable pullover", "exercise_type": "Tirón vertical", "pattern": "Polea", "equipment": "Polea alta", "subtype": "Similar a pullover con mancuerna"},
    {"muscle": "Espalda", "name": "Seated cable row V-bar", "exercise_type": "Tirón horizontal", "pattern": "Polea", "equipment": "Polea baja", "subtype": "Agarre neutro estrecho"},
    {"muscle": "Espalda", "name": "Wide-grip cable row", "exercise_type": "Tirón horizontal", "pattern": "Polea", "equipment": "Polea baja", "subtype": "Barra ancha"},
    {"muscle": "Espalda", "name": "One-arm cable row", "exercise_type": "Tirón horizontal", "pattern": "Polea", "equipment": "Polea baja/media", "subtype": "Unilateral de pie o sentado"},
    {"muscle": "Espalda", "name": "High-to-low cable row", "exercise_type": "Tirón diagonal", "pattern": "Polea", "equipment": "Alta a baja", "subtype": "Jalando de arriba hacia abajo"},
    {"muscle": "Espalda", "name": "Face pull", "exercise_type": "Tirón alto", "pattern": "Polea", "equipment": "Polea media/alta", "subtype": "Deltoide posterior + trapecio"},
    {"muscle": "Espalda", "name": "Cable rear delt row", "exercise_type": "Tirón alto", "pattern": "Polea", "equipment": "Polea alta", "subtype": "Row alto hacia pecho/cara"},
    {"muscle": "Espalda", "name": "Resistance band row", "exercise_type": "Tirón horizontal", "pattern": "Banda", "equipment": "Anclaje", "subtype": "Varias posiciones, casero"},
    {"muscle": "Espalda", "name": "Band lat pulldown", "exercise_type": "Tirón vertical", "pattern": "Banda", "equipment": "anclaje alto", "subtype": "Simula lat pulldown"},
    {"muscle": "Espalda", "name": "Band pull-apart", "exercise_type": "Abducción horizontal", "pattern": "Banda", "equipment": "De pie", "subtype": "Romboides, deltoide posterior"},
    {"muscle": "Espalda", "name": "Machine lat pulldown", "exercise_type": "Tirón vertical", "pattern": "Máquina", "equipment": "Selectorizada", "subtype": "Varias empuñaduras"},
    {"muscle": "Espalda", "name": "Plate-loaded lat pulldown", "exercise_type": "Tirón vertical", "pattern": "Máquina", "equipment": "Palanca (plate-loaded)", "subtype": "Unilateral/bilateral"},
    {"muscle": "Espalda", "name": "Seated cable row machine", "exercise_type": "Tirón horizontal", "pattern": "Máquina", "equipment": "Polea/selectorizada", "subtype": "Clásica de gimnasio"},
    {"muscle": "Espalda", "name": "Lever seated row (Hammer)", "exercise_type": "Tirón horizontal", "pattern": "Máquina", "equipment": "Palanca", "subtype": "Palancas independientes"},
    {"muscle": "Espalda", "name": "Chest-supported row machine", "exercise_type": "Tirón horizontal", "pattern": "Máquina", "equipment": "Palanca/selector", "subtype": "Pecho apoyado"},
    {"muscle": "Espalda", "name": "Machine high row", "exercise_type": "Tirón diagonal", "pattern": "Máquina", "equipment": "Palanca", "subtype": "Jalón alto hacia torso"},
    {"muscle": "Espalda", "name": "Machine reverse fly", "exercise_type": "Abducción horizontal", "pattern": "Máquina", "equipment": "Reverse pec-deck", "subtype": "Romboides + deltoide posterior"},
    {"muscle": "Espalda", "name": "Back extension 45°", "exercise_type": "Extensión columna", "pattern": "Máquina", "equipment": "Banco 45°", "subtype": "Erectores, glúteo, isquios"},
    {"muscle": "Espalda", "name": "Back extension horizontal", "exercise_type": "Extensión columna", "pattern": "Máquina", "equipment": "Roman chair", "subtype": "Versión horizontal"},
    {"muscle": "Espalda", "name": "Reverse hyper machine", "exercise_type": "Extensión posterior", "pattern": "Máquina", "equipment": "Reverse hyper", "subtype": "Glúteo + lumbar"},
    
    # ==================== PECHO ====================
    {"muscle": "Pecho", "name": "Push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Clásico; medio/inferior según ángulo"},
    {"muscle": "Pecho", "name": "Wide-grip push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Más pectoral, menos tríceps"},
    {"muscle": "Pecho", "name": "Diamond push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Mucho tríceps, pero sigue cargando pecho"},
    {"muscle": "Pecho", "name": "Incline push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Manos en banco/step", "subtype": "Más énfasis en parte inferior"},
    {"muscle": "Pecho", "name": "Decline push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Pies en banco", "subtype": "Más énfasis parte superior/clavicular"},
    {"muscle": "Pecho", "name": "Archer push-up", "exercise_type": "Empuje unilateral", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Un brazo trabaja más; mayor carga lateral"},
    {"muscle": "Pecho", "name": "Pseudo planche push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Mucho deltoide anterior y pecho"},
    {"muscle": "Pecho", "name": "Ring push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Anillas", "subtype": "Inestable, alta activación"},
    {"muscle": "Pecho", "name": "Ring fly", "exercise_type": "Apertura horizontal", "pattern": "Peso corporal", "equipment": "Anillas", "subtype": "Fly con peso corporal, muy avanzado"},
    {"muscle": "Pecho", "name": "Seal push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Manos elevadas", "subtype": "Mayor ROM en la parte baja"},
    {"muscle": "Pecho", "name": "Chest dip", "exercise_type": "Empuje vertical / diagonal", "pattern": "Peso corporal", "equipment": "Barras paralelas", "subtype": "Inclinando torso adelante, énfasis pectoral inferior"},
    {"muscle": "Pecho", "name": "Weighted chest dip", "exercise_type": "Empuje vertical / diagonal", "pattern": "Peso corporal + lastre", "equipment": "Barras paralelas", "subtype": "Igual que chest dip con carga"},
    {"muscle": "Pecho", "name": "Ring dip (pecho)", "exercise_type": "Empuje vertical / diagonal", "pattern": "Peso corporal", "equipment": "Anillas", "subtype": "Inestable, gran estímulo pectoral"},
    {"muscle": "Pecho", "name": "Bench press (flat)", "exercise_type": "Empuje horizontal", "pattern": "Barra", "equipment": "Banco plano", "subtype": "Pectoral esternal (medio/inferior)"},
    {"muscle": "Pecho", "name": "Close-grip bench press", "exercise_type": "Empuje horizontal", "pattern": "Barra", "equipment": "Banco plano", "subtype": "Menos pecho, más tríceps, pero press pecho"},
    {"muscle": "Pecho", "name": "Wide-grip bench press", "exercise_type": "Empuje horizontal", "pattern": "Barra", "equipment": "Banco plano", "subtype": "Mayor estiramiento y foco en pecho"},
    {"muscle": "Pecho", "name": "Pause bench press", "exercise_type": "Empuje horizontal", "pattern": "Barra", "equipment": "Banco plano", "subtype": "Pausa en pecho, más control/tensión"},
    {"muscle": "Pecho", "name": "Incline bench press", "exercise_type": "Empuje horizontal inclinado", "pattern": "Barra", "equipment": "Banco inclinado", "subtype": "Énfasis pectoral superior (clavicular)"},
    {"muscle": "Pecho", "name": "Low-incline bench press", "exercise_type": "Empuje horizontal inclinado", "pattern": "Barra", "equipment": "Banco ligeramente inclinado", "subtype": "Compromiso entre superior y medio"},
    {"muscle": "Pecho", "name": "Decline bench press", "exercise_type": "Empuje horizontal declinado", "pattern": "Barra", "equipment": "Banco declinado", "subtype": "Más pectoral inferior"},
    {"muscle": "Pecho", "name": "Guillotine bench press", "exercise_type": "Empuje horizontal", "pattern": "Barra", "equipment": "Banco plano", "subtype": "Foco fuerte en porción superior; cuidado con hombro"},
    {"muscle": "Pecho", "name": "Reverse-grip bench press", "exercise_type": "Empuje horizontal", "pattern": "Barra", "equipment": "Banco plano", "subtype": "Más énfasis en pecho superior"},
    {"muscle": "Pecho", "name": "Floor press (pecho)", "exercise_type": "Empuje horizontal parcial", "pattern": "Barra", "equipment": "Suelo", "subtype": "ROM reducido, foco mitad superior del movimiento"},
    {"muscle": "Pecho", "name": "Smith machine bench press (flat)", "exercise_type": "Empuje horizontal", "pattern": "Barra Smith", "equipment": "Banco plano", "subtype": "Trayectoria guiada"},
    {"muscle": "Pecho", "name": "Smith incline bench press", "exercise_type": "Empuje horizontal inclinado", "pattern": "Barra Smith", "equipment": "Banco inclinado", "subtype": "Upper chest controlado"},
    {"muscle": "Pecho", "name": "Smith decline bench press", "exercise_type": "Empuje horizontal declinado", "pattern": "Barra Smith", "equipment": "Banco declinado", "subtype": "Lower chest guiado"},
    {"muscle": "Pecho", "name": "DB bench press (flat)", "exercise_type": "Empuje horizontal", "pattern": "Mancuernas", "equipment": "Banco plano", "subtype": "Mayor rango que barra"},
    {"muscle": "Pecho", "name": "DB bench press (neutral grip)", "exercise_type": "Empuje horizontal", "pattern": "Mancuernas", "equipment": "Banco plano", "subtype": "Menos estrés hombro, buen pecho"},
    {"muscle": "Pecho", "name": "DB incline bench press", "exercise_type": "Empuje horizontal inclinado", "pattern": "Mancuernas", "equipment": "Banco inclinado", "subtype": "Pectoral superior"},
    {"muscle": "Pecho", "name": "DB low-incline press", "exercise_type": "Empuje horizontal inclinado", "pattern": "Mancuernas", "equipment": "Banco ligeramente inclinado", "subtype": "Punto medio hombro/pecho"},
    {"muscle": "Pecho", "name": "DB decline bench press", "exercise_type": "Empuje horizontal declinado", "pattern": "Mancuernas", "equipment": "Banco declinado", "subtype": "Más bajo/medio/inferior"},
    {"muscle": "Pecho", "name": "DB floor press", "exercise_type": "Empuje horizontal parcial", "pattern": "Mancuernas", "equipment": "Suelo", "subtype": "ROM reducido, seguro sin rack"},
    {"muscle": "Pecho", "name": "DB fly (flat)", "exercise_type": "Apertura horizontal", "pattern": "Mancuernas", "equipment": "Banco plano", "subtype": "Estiramiento pec esternal"},
    {"muscle": "Pecho", "name": "DB incline fly", "exercise_type": "Apertura horizontal", "pattern": "Mancuernas", "equipment": "Banco inclinado", "subtype": "Más parte superior"},
    {"muscle": "Pecho", "name": "DB decline fly", "exercise_type": "Apertura horizontal", "pattern": "Mancuernas", "equipment": "Banco declinado", "subtype": "Más fibras inferiores"},
    {"muscle": "Pecho", "name": "DB squeeze press", "exercise_type": "Empuje + aducción", "pattern": "Mancuernas", "equipment": "Banco plano", "subtype": "Mancuernas juntas, aducción constante"},
    {"muscle": "Pecho", "name": "DB pullover (pecho)", "exercise_type": "Flexión hombro", "pattern": "Mancuernas", "equipment": "Banco", "subtype": "Pectoral + dorsal (ejercicio híbrido)"},
    {"muscle": "Pecho", "name": "Single-arm DB bench press", "exercise_type": "Empuje unilateral", "pattern": "Mancuernas", "equipment": "Banco plano", "subtype": "Core anti-rotación + pecho"},
    {"muscle": "Pecho", "name": "Machine chest press (flat)", "exercise_type": "Empuje horizontal", "pattern": "Máquina", "equipment": "Chest press machine", "subtype": "Press de pecho medio/inferior guiado"},
    {"muscle": "Pecho", "name": "Machine incline chest press", "exercise_type": "Empuje horizontal inclinado", "pattern": "Máquina", "equipment": "Incline chest press", "subtype": "Upper chest guiado"},
    {"muscle": "Pecho", "name": "Machine decline chest press", "exercise_type": "Empuje horizontal declinado", "pattern": "Máquina", "equipment": "Decline chest press", "subtype": "Lower chest guiado"},
    {"muscle": "Pecho", "name": "Plate-loaded chest press", "exercise_type": "Empuje horizontal", "pattern": "Máquina", "equipment": "Palanca (plate-loaded)", "subtype": "Unilateral/bilateral"},
    {"muscle": "Pecho", "name": "Plate-loaded incline press", "exercise_type": "Empuje horizontal inclinado", "pattern": "Máquina", "equipment": "Palanca", "subtype": "Upper chest pesado"},
    {"muscle": "Pecho", "name": "Pec deck fly (machine)", "exercise_type": "Apertura horizontal", "pattern": "Máquina", "equipment": "Pec-deck", "subtype": "Aislante de pecho"},
    {"muscle": "Pecho", "name": "Cable chest press (standing)", "exercise_type": "Empuje horizontal", "pattern": "Polea", "equipment": "Dos poleas, de pie", "subtype": "Como press pero en poleas"},
    {"muscle": "Pecho", "name": "Cable chest press (lying)", "exercise_type": "Empuje horizontal", "pattern": "Polea", "equipment": "Banco entre poleas", "subtype": "Trazo similar a DB press con tensión constante"},
    {"muscle": "Pecho", "name": "High-to-low cable fly", "exercise_type": "Aducción diagonal", "pattern": "Polea", "equipment": "Poleas altas", "subtype": "Énfasis en pectoral inferior"},
    {"muscle": "Pecho", "name": "Low-to-high cable fly", "exercise_type": "Aducción diagonal", "pattern": "Polea", "equipment": "Poleas bajas", "subtype": "Énfasis en porción superior"},
    {"muscle": "Pecho", "name": "Mid-cable fly", "exercise_type": "Apertura horizontal", "pattern": "Polea", "equipment": "Poleas a altura pecho", "subtype": "Pectoral medio"},
    {"muscle": "Pecho", "name": "Single-arm cable fly", "exercise_type": "Apertura horizontal unilateral", "pattern": "Polea", "equipment": "Una polea", "subtype": "Ajustes finos de aducción"},
    {"muscle": "Pecho", "name": "Cable crossover (classic)", "exercise_type": "Apertura horizontal", "pattern": "Polea", "equipment": "Dos poleas", "subtype": "Desde alto a bajo o medio; muy usado"},
    {"muscle": "Pecho", "name": "Cable pullover (pecho)", "exercise_type": "Flexión hombro", "pattern": "Polea", "equipment": "Alta", "subtype": "Similar a DB pullover con tensión cable"},
    {"muscle": "Pecho", "name": "Landmine press", "exercise_type": "Empuje diagonal", "pattern": "Barra + landmine", "equipment": "De pie/rodillas", "subtype": "Mezcla hombro/pecho según ángulo"},
    {"muscle": "Pecho", "name": "Push-up on handles", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Asas / paralelas bajas", "subtype": "Mayor ROM, menos estrés muñeca"},
    {"muscle": "Pecho", "name": "Weighted push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal + lastre", "equipment": "Suelo", "subtype": "Versión cargada de push-up"},
    
    # ==================== BÍCEPS ====================
    {"muscle": "Bíceps", "name": "Chin-up (bíceps)", "exercise_type": "Flexión codo + tirón vertical", "pattern": "Peso corporal", "equipment": "Barra fija", "subtype": "Dominada supina, ancho/medio/estrecho"},
    {"muscle": "Bíceps", "name": "Neutral-grip chin-up", "exercise_type": "Flexión codo + tirón vertical", "pattern": "Peso corporal", "equipment": "Barra neutra", "subtype": "Palmas enfrentadas, más braquiorradial"},
    {"muscle": "Bíceps", "name": "Towel chin-up", "exercise_type": "Flexión codo + tirón vertical", "pattern": "Peso corporal", "equipment": "Barra + toallas", "subtype": "Agarre toalla, fuerte estímulo de agarre"},
    {"muscle": "Bíceps", "name": "Bodyweight arm curl", "exercise_type": "Flexión codo", "pattern": "Peso corporal", "equipment": "TRX/anillas", "subtype": "Suspended arm curl con cuerpo inclinado"},
    {"muscle": "Bíceps", "name": "Isometric hold chin-up", "exercise_type": "Isométrico", "pattern": "Peso corporal", "equipment": "Barra fija", "subtype": "Mantén flexión de codo 90° o arriba"},
    {"muscle": "Bíceps", "name": "Strict barbell curl", "exercise_type": "Flexión codo", "pattern": "Barra", "equipment": "Libre", "subtype": "De pie, torso fijo, agarre supino"},
    {"muscle": "Bíceps", "name": "Cheat barbell curl", "exercise_type": "Flexión codo", "pattern": "Barra", "equipment": "Libre", "subtype": "Mismo que strict pero con algo de impulso"},
    {"muscle": "Bíceps", "name": "Barbell curl (recta)", "exercise_type": "Flexión codo", "pattern": "Barra", "equipment": "Libre", "subtype": "Curl clásico con barra recta"},
    {"muscle": "Bíceps", "name": "EZ bar curl", "exercise_type": "Flexión codo", "pattern": "Barra EZ", "equipment": "Libre", "subtype": "Mismas mecánicas, menos estrés muñeca"},
    {"muscle": "Bíceps", "name": "Close-grip barbell curl", "exercise_type": "Flexión codo", "pattern": "Barra", "equipment": "Libre", "subtype": "Agarre estrecho, más parte externa bíceps"},
    {"muscle": "Bíceps", "name": "Wide-grip barbell curl", "exercise_type": "Flexión codo", "pattern": "Barra", "equipment": "Libre", "subtype": "Agarre ancho, más cabeza corta"},
    {"muscle": "Bíceps", "name": "Drag curl", "exercise_type": "Flexión codo", "pattern": "Barra", "equipment": "Libre", "subtype": "Barra arrastra por el torso"},
    {"muscle": "Bíceps", "name": "Barbell preacher curl", "exercise_type": "Flexión codo", "pattern": "Barra", "equipment": "Banco predicador", "subtype": "Bíceps aislado, brazo apoyado"},
    {"muscle": "Bíceps", "name": "Close-grip preacher curl", "exercise_type": "Flexión codo", "pattern": "Barra", "equipment": "Banco predicador", "subtype": "Versión agarre cerrado"},
    {"muscle": "Bíceps", "name": "Scott curl", "exercise_type": "Flexión codo", "pattern": "Barra", "equipment": "Banco Scott", "subtype": "Variante de preacher"},
    {"muscle": "Bíceps", "name": "Spider curl (barra)", "exercise_type": "Flexión codo", "pattern": "Barra", "equipment": "Banco inclinado", "subtype": "Pecho al banco, brazos colgando"},
    {"muscle": "Bíceps", "name": "21s barbell curl", "exercise_type": "Flexión codo", "pattern": "Barra", "equipment": "Libre", "subtype": "7+7+7 (parcial baja, alta y completa)"},
    {"muscle": "Bíceps", "name": "Strict curl (contra pared)", "exercise_type": "Flexión codo", "pattern": "Barra", "equipment": "Libre", "subtype": "Espalda a la pared, elimina balanceo"},
    {"muscle": "Bíceps", "name": "Landmine biceps curl", "exercise_type": "Flexión codo", "pattern": "Barra + landmine", "equipment": "Base landmine", "subtype": "Barra anclada, curl con agarre neutro"},
    {"muscle": "Bíceps", "name": "Standing DB curl", "exercise_type": "Flexión codo", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Alterno o simultáneo, supino"},
    {"muscle": "Bíceps", "name": "Seated DB curl", "exercise_type": "Flexión codo", "pattern": "Mancuernas", "equipment": "Banco", "subtype": "Sentado, menos ayuda del torso"},
    {"muscle": "Bíceps", "name": "Alternating DB curl", "exercise_type": "Flexión codo", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Alternas brazos"},
    {"muscle": "Bíceps", "name": "Simultaneous DB curl", "exercise_type": "Flexión codo", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Ambos brazos a la vez"},
    {"muscle": "Bíceps", "name": "Hammer curl", "exercise_type": "Flexión codo", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Agarre neutro (braquiorradial/braquial)"},
    {"muscle": "Bíceps", "name": "Cross-body hammer curl", "exercise_type": "Flexión codo", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Mancuerna hacia hombro opuesto"},
    {"muscle": "Bíceps", "name": "Incline DB curl", "exercise_type": "Flexión codo", "pattern": "Mancuernas", "equipment": "Banco inclinado", "subtype": "Mayor estiramiento bíceps"},
    {"muscle": "Bíceps", "name": "Lying DB curl", "exercise_type": "Flexión codo", "pattern": "Mancuernas", "equipment": "Banco plano", "subtype": "Tumbado, cambia curva de fuerza"},
    {"muscle": "Bíceps", "name": "Flat bench DB curl", "exercise_type": "Flexión codo", "pattern": "Mancuernas", "equipment": "Banco plano sentado", "subtype": "Variante sentada"},
    {"muscle": "Bíceps", "name": "Concentration curl", "exercise_type": "Flexión codo", "pattern": "Mancuernas", "equipment": "Sentado", "subtype": "Brazo apoyado en muslo interno"},
    {"muscle": "Bíceps", "name": "DB preacher curl", "exercise_type": "Flexión codo", "pattern": "Mancuernas", "equipment": "Banco predicador", "subtype": "Variante unilateral"},
    {"muscle": "Bíceps", "name": "Spider curl (DB)", "exercise_type": "Flexión codo", "pattern": "Mancuernas", "equipment": "Banco inclinado", "subtype": "Como la de barra pero con DB"},
    {"muscle": "Bíceps", "name": "Waiter curl", "exercise_type": "Flexión codo", "pattern": "Mancuernas/disco", "equipment": "Libre", "subtype": "Sosteniendo DB/disco como bandeja"},
    {"muscle": "Bíceps", "name": "Zottman curl", "exercise_type": "Flexión codo + pron/sup", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Subes supino, bajas prono"},
    {"muscle": "Bíceps", "name": "Inverse Zottman curl", "exercise_type": "Flexión codo + pron/sup", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Variante enfatizando excéntrica diferente"},
    {"muscle": "Bíceps", "name": "Bayesian cable curl", "exercise_type": "Flexión codo", "pattern": "Polea", "equipment": "Baja, de espaldas", "subtype": "Estiramiento grande, cuerpo adelantado"},
    {"muscle": "Bíceps", "name": "Standard cable curl", "exercise_type": "Flexión codo", "pattern": "Polea", "equipment": "Baja", "subtype": "Barra recta/EZ, de pie"},
    {"muscle": "Bíceps", "name": "Cable rope curl", "exercise_type": "Flexión codo", "pattern": "Polea", "equipment": "Baja", "subtype": "Cuerda, puedes rotar al final"},
    {"muscle": "Bíceps", "name": "Close-grip cable curl", "exercise_type": "Flexión codo", "pattern": "Polea", "equipment": "Baja", "subtype": "Agarre cerrado con barra"},
    {"muscle": "Bíceps", "name": "One-arm cable curl", "exercise_type": "Flexión codo", "pattern": "Polea", "equipment": "Baja", "subtype": "Unilateral, mango individual"},
    {"muscle": "Bíceps", "name": "High cable curl (double)", "exercise_type": "Flexión codo", "pattern": "Polea", "equipment": "Dos poleas altas", "subtype": "Brazos en cruz hacia cabeza"},
    {"muscle": "Bíceps", "name": "Overhead cable curl", "exercise_type": "Flexión codo", "pattern": "Polea", "equipment": "Alta", "subtype": "Curl llevando manos hacia frente/cabeza"},
    {"muscle": "Bíceps", "name": "Reverse cable curl", "exercise_type": "Flexión codo", "pattern": "Polea", "equipment": "Baja", "subtype": "Pronado, más braquiorradial"},
    {"muscle": "Bíceps", "name": "Machine biceps curl (sentado)", "exercise_type": "Flexión codo", "pattern": "Máquina", "equipment": "Selectorizada", "subtype": "Curl sentado clásico"},
    {"muscle": "Bíceps", "name": "Plate-loaded biceps machine", "exercise_type": "Flexión codo", "pattern": "Máquina", "equipment": "Palanca (plate-loaded)", "subtype": "Unilateral/bilateral"},
    {"muscle": "Bíceps", "name": "Machine preacher curl", "exercise_type": "Flexión codo", "pattern": "Máquina", "equipment": "Predicador", "subtype": "Apoyo tipo Scott/preacher"},
    {"muscle": "Bíceps", "name": "Cable preacher machine", "exercise_type": "Flexión codo", "pattern": "Máquina/polea", "equipment": "Predicador con cable", "subtype": "Tensión continua del cable"},
    
    # ==================== TRÍCEPS ====================
    {"muscle": "Tríceps", "name": "Close-grip push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Manos más juntas, más énfasis tríceps"},
    {"muscle": "Tríceps", "name": "Diamond push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Manos en triángulo; altísima activación EMG"},
    {"muscle": "Tríceps", "name": "Triceps triangle push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Variante de diamond/triangle"},
    {"muscle": "Tríceps", "name": "Close-grip bench push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Manos en banco", "subtype": "Menos carga que en suelo"},
    {"muscle": "Tríceps", "name": "Bench dip", "exercise_type": "Empuje vertical", "pattern": "Peso corporal", "equipment": "Bancos", "subtype": "Pies en suelo o elevado, énfasis tríceps"},
    {"muscle": "Tríceps", "name": "Parallel bar dip (triceps)", "exercise_type": "Empuje vertical", "pattern": "Peso corporal", "equipment": "Barras paralelas", "subtype": "Tronco más vertical, codos pegados"},
    {"muscle": "Tríceps", "name": "Ring dip (tríceps)", "exercise_type": "Empuje vertical", "pattern": "Peso corporal", "equipment": "Anillas", "subtype": "Inestable, alta demanda"},
    {"muscle": "Tríceps", "name": "Close-grip dip", "exercise_type": "Empuje vertical", "pattern": "Peso corporal", "equipment": "Barras paralelas", "subtype": "Agarre más cerrado, más tríceps"},
    {"muscle": "Tríceps", "name": "Isometric hold dip", "exercise_type": "Isométrico", "pattern": "Peso corporal", "equipment": "Barras paralelas", "subtype": "Mantener codos cerca de 90°"},
    {"muscle": "Tríceps", "name": "Close-grip bench press", "exercise_type": "Empuje horizontal", "pattern": "Barra", "equipment": "Banca", "subtype": "Manos estrechas, gran carga para tríceps"},
    {"muscle": "Tríceps", "name": "Reverse-grip close bench press", "exercise_type": "Empuje horizontal", "pattern": "Barra", "equipment": "Banca", "subtype": "Agarre supino, cambia énfasis cabeza medial"},
    {"muscle": "Tríceps", "name": "Board press", "exercise_type": "Empuje horizontal", "pattern": "Barra", "equipment": "Banca + tablas", "subtype": "Parcial superior, foco tríceps"},
    {"muscle": "Tríceps", "name": "Floor press", "exercise_type": "Empuje horizontal", "pattern": "Barra", "equipment": "Suelo", "subtype": "Recorte ROM, gran carga"},
    {"muscle": "Tríceps", "name": "JM press", "exercise_type": "Empuje mixto", "pattern": "Barra", "equipment": "Banca", "subtype": "Híbrido press + extensión (muy de powerlifting)"},
    {"muscle": "Tríceps", "name": "Close-grip Smith machine press", "exercise_type": "Empuje horizontal", "pattern": "Barra Smith", "equipment": "Banca", "subtype": "Más control de trayectoria"},
    {"muscle": "Tríceps", "name": "Lying barbell triceps extension (skullcrusher)", "exercise_type": "Extensión codo", "pattern": "Barra", "equipment": "Banca plana", "subtype": "Flex/extensión codo, barra hacia frente/cabeza"},
    {"muscle": "Tríceps", "name": "Incline skullcrusher", "exercise_type": "Extensión codo", "pattern": "Barra", "equipment": "Banco inclinado", "subtype": "Más estiramiento en cabeza larga"},
    {"muscle": "Tríceps", "name": "Decline skullcrusher", "exercise_type": "Extensión codo", "pattern": "Barra", "equipment": "Banco declinado", "subtype": "ROM y sensación distintos"},
    {"muscle": "Tríceps", "name": "EZ-bar skullcrusher", "exercise_type": "Extensión codo", "pattern": "Barra EZ", "equipment": "Banca", "subtype": "Menos estrés muñeca"},
    {"muscle": "Tríceps", "name": "Lying French press", "exercise_type": "Extensión codo", "pattern": "Barra", "equipment": "Banca", "subtype": "Variante clásica press francés"},
    {"muscle": "Tríceps", "name": "Overhead EZ-bar triceps extension", "exercise_type": "Extensión codo", "pattern": "Barra EZ", "equipment": "Sentado/de pie", "subtype": "Por encima de la cabeza, enfatiza cabeza larga"},
    {"muscle": "Tríceps", "name": "Seated overhead EZ extension", "exercise_type": "Extensión codo", "pattern": "Barra EZ", "equipment": "Sentado", "subtype": "Respaldo, más estabilidad"},
    {"muscle": "Tríceps", "name": "Standing overhead bar extension", "exercise_type": "Extensión codo", "pattern": "Barra", "equipment": "De pie", "subtype": "Más demanda de core"},
    {"muscle": "Tríceps", "name": "Rolling triceps extension", "exercise_type": "Extensión codo + pullover", "pattern": "Barra", "equipment": "Banca", "subtype": "Combina skullcrusher + pullover"},
    {"muscle": "Tríceps", "name": "Barbell kickback", "exercise_type": "Extensión codo", "pattern": "Barra corta", "equipment": "Libre", "subtype": "Menos común, similar a DB kickback"},
    {"muscle": "Tríceps", "name": "Flat DB triceps extension", "exercise_type": "Extensión codo", "pattern": "Mancuernas", "equipment": "Banco plano", "subtype": "Similar a skullcrusher con barra"},
    {"muscle": "Tríceps", "name": "Incline DB triceps extension", "exercise_type": "Extensión codo", "pattern": "Mancuernas", "equipment": "Banco inclinado", "subtype": "Mayor estiramiento"},
    {"muscle": "Tríceps", "name": "Decline DB triceps extension", "exercise_type": "Extensión codo", "pattern": "Mancuernas", "equipment": "Banco declinado", "subtype": "Modifica curva de fuerza"},
    {"muscle": "Tríceps", "name": "DB French press (dos manos)", "exercise_type": "Extensión codo", "pattern": "Mancuernas", "equipment": "Sentado/de pie", "subtype": "Una mancuerna sujeta con ambas manos"},
    {"muscle": "Tríceps", "name": "One-arm overhead DB extension", "exercise_type": "Extensión codo", "pattern": "Mancuernas", "equipment": "Sentado/de pie", "subtype": "Unilateral, corrige desbalances"},
    {"muscle": "Tríceps", "name": "DB kickback", "exercise_type": "Extensión codo", "pattern": "Mancuernas", "equipment": "Banco / torso inclinado", "subtype": "Brazo paralelo al suelo, extiendes codo"},
    {"muscle": "Tríceps", "name": "Standing DB kickback", "exercise_type": "Extensión codo", "pattern": "Mancuernas", "equipment": "De pie", "subtype": "Similar pero sin apoyo"},
    {"muscle": "Tríceps", "name": "Cross-body DB kickback", "exercise_type": "Extensión codo", "pattern": "Mancuernas", "equipment": "Banco", "subtype": "Llevar DB algo hacia dentro"},
    {"muscle": "Tríceps", "name": "Close-grip DB press", "exercise_type": "Empuje horizontal", "pattern": "Mancuernas", "equipment": "Banca", "subtype": "Mancuernas pegadas, foco tríceps"},
    {"muscle": "Tríceps", "name": "Neutral-grip DB press (tríceps)", "exercise_type": "Empuje horizontal", "pattern": "Mancuernas", "equipment": "Banca", "subtype": "Agarre neutro, codos pegados"},
    {"muscle": "Tríceps", "name": "Tate press", "exercise_type": "Extensión codo", "pattern": "Mancuernas", "equipment": "Banca", "subtype": "DB parten sobre pecho, codos abiertos"},
    {"muscle": "Tríceps", "name": "KB overhead triceps extension", "exercise_type": "Extensión codo", "pattern": "Kettlebell", "equipment": "De pie/sentado", "subtype": "Una o dos manos, similar a DB"},
    {"muscle": "Tríceps", "name": "KB floor skullcrusher", "exercise_type": "Extensión codo", "pattern": "Kettlebell", "equipment": "Suelo", "subtype": "Variante tumbado"},
    {"muscle": "Tríceps", "name": "Rope triceps pushdown", "exercise_type": "Extensión codo", "pattern": "Polea", "equipment": "Alta, cuerda", "subtype": "Separando cuerda al final"},
    {"muscle": "Tríceps", "name": "Straight-bar triceps pushdown", "exercise_type": "Extensión codo", "pattern": "Polea", "equipment": "Alta, barra recta", "subtype": "Pronado"},
    {"muscle": "Tríceps", "name": "V-bar triceps pushdown", "exercise_type": "Extensión codo", "pattern": "Polea", "equipment": "Alta, barra V", "subtype": "Agarre neutro"},
    {"muscle": "Tríceps", "name": "Reverse-grip pushdown", "exercise_type": "Extensión codo", "pattern": "Polea", "equipment": "Alta, barra recta", "subtype": "Supino, énfasis cabeza medial"},
    {"muscle": "Tríceps", "name": "One-arm cable pushdown", "exercise_type": "Extensión codo", "pattern": "Polea", "equipment": "Alta, mango", "subtype": "Unilateral"},
    {"muscle": "Tríceps", "name": "Overhead cable triceps extension", "exercise_type": "Extensión codo", "pattern": "Polea", "equipment": "Alta, de espaldas", "subtype": "Brazos sobre cabeza"},
    {"muscle": "Tríceps", "name": "Overhead cable rope extension", "exercise_type": "Extensión codo", "pattern": "Polea", "equipment": "Alta, cuerda", "subtype": "Mayor libertad de muñeca"},
    {"muscle": "Tríceps", "name": "Katana cable extension", "exercise_type": "Extensión codo", "pattern": "Polea", "equipment": "Alta, cuerda", "subtype": "Brazos ligeramente en diagonal (tipo katana)"},
    {"muscle": "Tríceps", "name": "Cable triceps pushaway", "exercise_type": "Extensión codo", "pattern": "Polea", "equipment": "Alta", "subtype": "Desde frente hacia abajo/atrás; gran estiramiento"},
    {"muscle": "Tríceps", "name": "Cable kickback", "exercise_type": "Extensión codo", "pattern": "Polea", "equipment": "Baja", "subtype": "Simula DB kickback con tensión constante"},
    {"muscle": "Tríceps", "name": "Lying cable triceps extension", "exercise_type": "Extensión codo", "pattern": "Polea", "equipment": "Baja, tumbado", "subtype": "Similar a skullcrusher pero con cable"},
    {"muscle": "Tríceps", "name": "Machine triceps extension", "exercise_type": "Extensión codo", "pattern": "Máquina", "equipment": "Selectorizada", "subtype": "Codos fijos, patrón guiado"},
    {"muscle": "Tríceps", "name": "Plate-loaded triceps machine", "exercise_type": "Extensión codo", "pattern": "Máquina", "equipment": "Palanca (plate-loaded)", "subtype": "Unilateral/bilateral"},
    {"muscle": "Tríceps", "name": "Machine dip (tríceps)", "exercise_type": "Empuje vertical", "pattern": "Máquina", "equipment": "Dip machine", "subtype": "Configura para énfasis tríceps"},
    {"muscle": "Tríceps", "name": "Cable-assisted dip", "exercise_type": "Empuje vertical", "pattern": "Máquina/polea", "equipment": "Asistida", "subtype": "Misma mecánica con ayuda"},
    
    # ==================== CUÁDRICEPS ====================
    {"muscle": "Cuádriceps", "name": "Air squat", "exercise_type": "Sentadilla", "pattern": "Peso corporal", "equipment": "Libre", "subtype": "Sentadilla básica sin carga"},
    {"muscle": "Cuádriceps", "name": "Jump squat", "exercise_type": "Sentadilla + potencia", "pattern": "Peso corporal", "equipment": "Libre", "subtype": "Sentadilla con salto explosivo"},
    {"muscle": "Cuádriceps", "name": "Half squat", "exercise_type": "Sentadilla parcial", "pattern": "Peso corporal", "equipment": "Libre", "subtype": "ROM parcial, menos demanda"},
    {"muscle": "Cuádriceps", "name": "Full deep squat", "exercise_type": "Sentadilla profunda", "pattern": "Peso corporal", "equipment": "Libre", "subtype": "Glúteo + cuádriceps, movilidad alta"},
    {"muscle": "Cuádriceps", "name": "Wall sit", "exercise_type": "Isométrico cuádriceps", "pattern": "Peso corporal", "equipment": "Pared", "subtype": "Mantener 90° en rodillas"},
    {"muscle": "Cuádriceps", "name": "Assisted sissy squat", "exercise_type": "Squad aislante", "pattern": "Peso corporal", "equipment": "Sujeción a barra/soporte", "subtype": "Rodillas adelante, torso atrás"},
    {"muscle": "Cuádriceps", "name": "Free sissy squat", "exercise_type": "Squad aislante", "pattern": "Peso corporal", "equipment": "Libre", "subtype": "Muy exigente, gran tensión en cuádriceps"},
    {"muscle": "Cuádriceps", "name": "Kneeling quad extension", "exercise_type": "Extensión rodilla", "pattern": "Peso corporal", "equipment": "Arrodillado", "subtype": "Desde rodillas hacia atrás y adelante"},
    {"muscle": "Cuádriceps", "name": "Step-up", "exercise_type": "Dominante rodilla", "pattern": "Peso corporal", "equipment": "Banco/step", "subtype": "Altura define énfasis cuádriceps/glúteo"},
    {"muscle": "Cuádriceps", "name": "Step-down", "exercise_type": "Dominante rodilla", "pattern": "Peso corporal", "equipment": "Desde banco", "subtype": "Control excéntrico bajando del banco"},
    {"muscle": "Cuádriceps", "name": "Walking lunge", "exercise_type": "Zancada", "pattern": "Peso corporal", "equipment": "Libre", "subtype": "Adelante/caminar, quad + glúteo"},
    {"muscle": "Cuádriceps", "name": "Reverse lunge", "exercise_type": "Zancada", "pattern": "Peso corporal", "equipment": "Libre", "subtype": "Paso atrás, algo más cadera"},
    {"muscle": "Cuádriceps", "name": "Split squat", "exercise_type": "Zancada estática", "pattern": "Peso corporal", "equipment": "Libre", "subtype": "Postura fija, foco quad/glúteo"},
    {"muscle": "Cuádriceps", "name": "Bulgarian split squat", "exercise_type": "Zancada unilateral", "pattern": "Peso corporal", "equipment": "Pie trasero elevado", "subtype": "Mucho quad y glúteo pierna delantera"},
    {"muscle": "Cuádriceps", "name": "Lateral/side lunge", "exercise_type": "Zancada lateral", "pattern": "Peso corporal", "equipment": "Libre", "subtype": "Cuádriceps + aductores"},
    {"muscle": "Cuádriceps", "name": "Pistol squat", "exercise_type": "Sentadilla unilateral", "pattern": "Peso corporal", "equipment": "Libre", "subtype": "Muy avanzada, gran demanda quad"},
    {"muscle": "Cuádriceps", "name": "Heels-elevated squat", "exercise_type": "Sentadilla", "pattern": "Peso corporal", "equipment": "Talones elevados", "subtype": "Más énfasis cuádriceps"},
    {"muscle": "Cuádriceps", "name": "Barbell back squat (high bar)", "exercise_type": "Sentadilla", "pattern": "Barra", "equipment": "Libre", "subtype": "Muy clásico para cuádriceps"},
    {"muscle": "Cuádriceps", "name": "Barbell back squat (low bar)", "exercise_type": "Sentadilla", "pattern": "Barra", "equipment": "Libre", "subtype": "Más cadera, pero quad sigue activo"},
    {"muscle": "Cuádriceps", "name": "Front squat", "exercise_type": "Sentadilla frontal", "pattern": "Barra", "equipment": "Libre", "subtype": "Más torso vertical, más cuádriceps"},
    {"muscle": "Cuádriceps", "name": "Box squat", "exercise_type": "Sentadilla hacia caja", "pattern": "Barra", "equipment": "Caja", "subtype": "Control ROM, se usa según altura"},
    {"muscle": "Cuádriceps", "name": "Pause squat", "exercise_type": "Sentadilla pausada", "pattern": "Barra", "equipment": "Libre", "subtype": "Pausa en el fondo, más tensión"},
    {"muscle": "Cuádriceps", "name": "Tempo squat", "exercise_type": "Sentadilla tempo", "pattern": "Barra", "equipment": "Libre", "subtype": "Descenso/controlado, foco en tiempo bajo tensión"},
    {"muscle": "Cuádriceps", "name": "Zercher squat", "exercise_type": "Sentadilla frontal baja", "pattern": "Barra", "equipment": "Barra en codos", "subtype": "Cuádriceps + core"},
    {"muscle": "Cuádriceps", "name": "Barbell hack squat", "exercise_type": "Sentadilla", "pattern": "Barra", "equipment": "Barra detrás cuerpo", "subtype": "Variante clásica estilo hack"},
    {"muscle": "Cuádriceps", "name": "Barbell lunge", "exercise_type": "Zancada", "pattern": "Barra", "equipment": "Libre", "subtype": "Adelante/caminar, quad + glúteo"},
    {"muscle": "Cuádriceps", "name": "Barbell reverse lunge", "exercise_type": "Zancada", "pattern": "Barra", "equipment": "Libre", "subtype": "Paso atrás"},
    {"muscle": "Cuádriceps", "name": "Barbell split squat", "exercise_type": "Zancada estática", "pattern": "Barra", "equipment": "Libre", "subtype": "Similar a DB split pero con barra"},
    {"muscle": "Cuádriceps", "name": "Barbell step-up", "exercise_type": "Dominante rodilla", "pattern": "Barra", "equipment": "Banco", "subtype": "Subida al banco con barra"},
    {"muscle": "Cuádriceps", "name": "Goblet squat", "exercise_type": "Sentadilla", "pattern": "Mancuernas/Kettlebell", "equipment": "Cargada frontal", "subtype": "Buen patrón para quad"},
    {"muscle": "Cuádriceps", "name": "DB front squat", "exercise_type": "Sentadilla frontal", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Mancuernas en hombros"},
    {"muscle": "Cuádriceps", "name": "DB squat", "exercise_type": "Sentadilla", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Tipo suitcase"},
    {"muscle": "Cuádriceps", "name": "DB walking lunge", "exercise_type": "Zancada", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Clásico para quad"},
    {"muscle": "Cuádriceps", "name": "DB reverse lunge", "exercise_type": "Zancada", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Paso atrás"},
    {"muscle": "Cuádriceps", "name": "DB Bulgarian split squat", "exercise_type": "Zancada unilateral", "pattern": "Mancuernas", "equipment": "Pie trasero elevado", "subtype": "Muy usado para quad"},
    {"muscle": "Cuádriceps", "name": "DB step-up", "exercise_type": "Dominante rodilla", "pattern": "Mancuernas", "equipment": "Banco", "subtype": "Buen ejercicio unilateral"},
    {"muscle": "Cuádriceps", "name": "DB lateral lunge", "exercise_type": "Zancada lateral", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Quad + aductores"},
    {"muscle": "Cuádriceps", "name": "DB squat jump", "exercise_type": "Potencia", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Saltos con ligera carga"},
    {"muscle": "Cuádriceps", "name": "Sissy squat (weighted)", "exercise_type": "Aislante quad", "pattern": "Mancuernas/disco", "equipment": "Libre", "subtype": "Sissy con carga"},
    {"muscle": "Cuádriceps", "name": "KB goblet squat", "exercise_type": "Sentadilla", "pattern": "Kettlebell", "equipment": "Goblet", "subtype": "Similar a DB goblet"},
    {"muscle": "Cuádriceps", "name": "KB front rack squat", "exercise_type": "Sentadilla frontal", "pattern": "Kettlebell", "equipment": "Rack bilateral", "subtype": "Kettlebells en rack"},
    {"muscle": "Cuádriceps", "name": "KB lunge", "exercise_type": "Zancada", "pattern": "Kettlebell", "equipment": "Libre", "subtype": "Una o dos KB en rack o a lados"},
    {"muscle": "Cuádriceps", "name": "KB step-up", "exercise_type": "Dominante rodilla", "pattern": "Kettlebell", "equipment": "Banco", "subtype": "Variación de step-up"},
    {"muscle": "Cuádriceps", "name": "Cable squat", "exercise_type": "Sentadilla", "pattern": "Polea", "equipment": "Baja, mango", "subtype": "Squat tirando del cable adelante"},
    {"muscle": "Cuádriceps", "name": "Cable front squat", "exercise_type": "Sentadilla frontal", "pattern": "Polea", "equipment": "Baja", "subtype": "Cable en frente, patrón front squat"},
    {"muscle": "Cuádriceps", "name": "Cable split squat", "exercise_type": "Zancada", "pattern": "Polea", "equipment": "Baja", "subtype": "Cable frente al cuerpo, estabilidad extra"},
    {"muscle": "Cuádriceps", "name": "Cable step-up", "exercise_type": "Dominante rodilla", "pattern": "Polea", "equipment": "Baja", "subtype": "Menos habitual, pero posible"},
    {"muscle": "Cuádriceps", "name": "Standing cable leg extension", "exercise_type": "Extensión rodilla", "pattern": "Polea", "equipment": "Tobillera", "subtype": "Cuádriceps unilateral de pie"},
    {"muscle": "Cuádriceps", "name": "Resistance band squat", "exercise_type": "Sentadilla", "pattern": "Banda", "equipment": "Bajo pies + hombros", "subtype": "Ayuda o resistencia extra"},
    {"muscle": "Cuádriceps", "name": "Band-resisted squat jump", "exercise_type": "Potencia", "pattern": "Banda", "equipment": "Sujeto a cintura", "subtype": "Saltos con resistencia"},
    {"muscle": "Cuádriceps", "name": "Band leg extension", "exercise_type": "Extensión rodilla", "pattern": "Banda", "equipment": "Tobillo + anclaje", "subtype": "Variante casera de leg extension"},
    {"muscle": "Cuádriceps", "name": "Leg extension machine", "exercise_type": "Extensión rodilla", "pattern": "Máquina", "equipment": "Selectorizada", "subtype": "Aíslante de cuádriceps"},
    {"muscle": "Cuádriceps", "name": "Single-leg leg extension", "exercise_type": "Extensión rodilla", "pattern": "Máquina", "equipment": "Selectorizada", "subtype": "Unilateral, corrige desbalances"},
    {"muscle": "Cuádriceps", "name": "45° leg press (feet low)", "exercise_type": "Prensa piernas", "pattern": "Máquina", "equipment": "Sled 45°", "subtype": "Pies más bajos = más cuádriceps"},
    {"muscle": "Cuádriceps", "name": "45° leg press", "exercise_type": "Prensa piernas", "pattern": "Máquina", "equipment": "Sled 45°", "subtype": "Trabajo global pierna, buen quad"},
    {"muscle": "Cuádriceps", "name": "Horizontal leg press", "exercise_type": "Prensa piernas", "pattern": "Máquina", "equipment": "Horizontal", "subtype": "Similar enfoque al 45°"},
    {"muscle": "Cuádriceps", "name": "Single-leg press", "exercise_type": "Prensa unilateral", "pattern": "Máquina", "equipment": "Cualquier tipo", "subtype": "Más énfasis cada pierna"},
    {"muscle": "Cuádriceps", "name": "Hack squat machine", "exercise_type": "Sentadilla guiada", "pattern": "Máquina", "equipment": "Hack", "subtype": "Gran enfoque en cuádriceps según pies"},
    {"muscle": "Cuádriceps", "name": "V-squat machine", "exercise_type": "Sentadilla guiada", "pattern": "Máquina", "equipment": "V-squat", "subtype": "Variante hack/press híbrida"},
    {"muscle": "Cuádriceps", "name": "Pendulum squat", "exercise_type": "Sentadilla guiada", "pattern": "Máquina", "equipment": "Pendulum", "subtype": "Permite gran ROM quad"},
    {"muscle": "Cuádriceps", "name": "Smith machine squat", "exercise_type": "Sentadilla", "pattern": "Smith", "equipment": "Barra Smith", "subtype": "Sentadilla guiada"},
    {"muscle": "Cuádriceps", "name": "Smith front squat", "exercise_type": "Sentadilla frontal", "pattern": "Smith", "equipment": "Barra Smith", "subtype": "Más fácil el equilibrio"},
    {"muscle": "Cuádriceps", "name": "Smith split squat / Bulgarian", "exercise_type": "Zancada guiada", "pattern": "Smith", "equipment": "Barra Smith", "subtype": "Excelente para quad unilateral"},
    {"muscle": "Cuádriceps", "name": "Smith hack squat", "exercise_type": "Sentadilla", "pattern": "Smith", "equipment": "Barra detrás", "subtype": "Simula hack"},
    
    # ==================== HOMBRO ====================
    {"muscle": "Hombro", "name": "Pike push-up", "exercise_type": "Empuje vertical", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Versión inclinada, énfasis deltoide anterior"},
    {"muscle": "Hombro", "name": "Elevated pike push-up", "exercise_type": "Empuje vertical", "pattern": "Peso corporal", "equipment": "Pies en banco", "subtype": "Más vertical, más hombro"},
    {"muscle": "Hombro", "name": "Handstand push-up", "exercise_type": "Empuje vertical", "pattern": "Peso corporal", "equipment": "Wall HSPU", "subtype": "Muy demandante, anterior/lateral"},
    {"muscle": "Hombro", "name": "Free handstand push-up", "exercise_type": "Empuje vertical", "pattern": "Peso corporal", "equipment": "Libre", "subtype": "Variante sin apoyo, muy avanzada"},
    {"muscle": "Hombro", "name": "Decline push-up (hombro)", "exercise_type": "Empuje horizontal/vertical", "pattern": "Peso corporal", "equipment": "Pies elevados", "subtype": "Aumenta componente hombro"},
    {"muscle": "Hombro", "name": "Planche lean push-up", "exercise_type": "Empuje horizontal", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Mucho deltoide anterior"},
    {"muscle": "Hombro", "name": "Y-T-W en suelo", "exercise_type": "Aislante posterior", "pattern": "Peso corporal", "equipment": "Tumbado prono", "subtype": "Deltoide posterior + trapecio"},
    {"muscle": "Hombro", "name": "Barbell overhead press (standing)", "exercise_type": "Empuje vertical", "pattern": "Barra", "equipment": "Libre", "subtype": "Press militar clásico"},
    {"muscle": "Hombro", "name": "Seated barbell overhead press", "exercise_type": "Empuje vertical", "pattern": "Barra", "equipment": "Sentado", "subtype": "Menos demanda de core"},
    {"muscle": "Hombro", "name": "Push press", "exercise_type": "Empuje vertical + pierna", "pattern": "Barra", "equipment": "Libre", "subtype": "Usa impulso de piernas"},
    {"muscle": "Hombro", "name": "Behind-the-neck press", "exercise_type": "Empuje vertical", "pattern": "Barra", "equipment": "Libre", "subtype": "Más estiramiento, no para todos"},
    {"muscle": "Hombro", "name": "Upright row", "exercise_type": "Tirón vertical", "pattern": "Barra", "equipment": "Libre", "subtype": "Deltoide lateral + trapecio"},
    {"muscle": "Hombro", "name": "Barbell front raise", "exercise_type": "Elevación frontal", "pattern": "Barra", "equipment": "Libre", "subtype": "Aislante deltoide anterior"},
    {"muscle": "Hombro", "name": "Barbell rear delt row", "exercise_type": "Remo alto", "pattern": "Barra", "equipment": "Libre", "subtype": "Tronco inclinado, foco deltoide posterior"},
    {"muscle": "Hombro", "name": "Smith machine shoulder press", "exercise_type": "Empuje vertical", "pattern": "Smith", "equipment": "Máquina", "subtype": "Trayectoria guiada"},
    {"muscle": "Hombro", "name": "Barbell overhead carry", "exercise_type": "Estabilidad overhead", "pattern": "Barra", "equipment": "Libre", "subtype": "Mantener barra por encima de cabeza"},
    {"muscle": "Hombro", "name": "DB shoulder press (standing)", "exercise_type": "Empuje vertical", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Anterior/lateral"},
    {"muscle": "Hombro", "name": "Seated DB shoulder press", "exercise_type": "Empuje vertical", "pattern": "Mancuernas", "equipment": "Sentado", "subtype": "Variante muy usada"},
    {"muscle": "Hombro", "name": "One-arm DB shoulder press", "exercise_type": "Empuje vertical", "pattern": "Mancuernas", "equipment": "De pie/sentado", "subtype": "Unilateral, más core"},
    {"muscle": "Hombro", "name": "Arnold press", "exercise_type": "Empuje vertical", "pattern": "Mancuernas", "equipment": "Sentado/de pie", "subtype": "Rotación interna-externa, mucho anterior"},
    {"muscle": "Hombro", "name": "DB push press", "exercise_type": "Empuje vertical + pierna", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Similar a push press con barra"},
    {"muscle": "Hombro", "name": "DB lateral raise (de pie)", "exercise_type": "Abducción", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Deltoide lateral"},
    {"muscle": "Hombro", "name": "Seated DB lateral raise", "exercise_type": "Abducción", "pattern": "Mancuernas", "equipment": "Sentado", "subtype": "Menos balanceo"},
    {"muscle": "Hombro", "name": "Leaning lateral raise", "exercise_type": "Abducción", "pattern": "Mancuernas", "equipment": "Sujeto a soporte", "subtype": "Mayor ROM en lateral"},
    {"muscle": "Hombro", "name": "Incline lateral raise", "exercise_type": "Abducción", "pattern": "Mancuernas", "equipment": "Banco inclinado", "subtype": "Cambia curva de fuerza"},
    {"muscle": "Hombro", "name": "DB front raise", "exercise_type": "Elevación frontal", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Deltoide anterior"},
    {"muscle": "Hombro", "name": "Alternating front raise", "exercise_type": "Elevación frontal", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Un brazo a la vez"},
    {"muscle": "Hombro", "name": "DB rear delt fly (bent-over)", "exercise_type": "Abducción horizontal", "pattern": "Mancuernas", "equipment": "Tronco inclinado", "subtype": "Clásico posterior"},
    {"muscle": "Hombro", "name": "Seated bent-over rear delt raise", "exercise_type": "Abducción horizontal", "pattern": "Mancuernas", "equipment": "Sentado, tronco inclinado", "subtype": "Deltoide posterior puro"},
    {"muscle": "Hombro", "name": "Lying rear lateral raise", "exercise_type": "Abducción horizontal", "pattern": "Mancuernas", "equipment": "Tumbado prono en banco", "subtype": "Aísla bien posterior"},
    {"muscle": "Hombro", "name": "DB rear delt row", "exercise_type": "Remo hacia lateral", "pattern": "Mancuernas", "equipment": "Banco/apoyo", "subtype": "Remo alto hacia afuera"},
    {"muscle": "Hombro", "name": "Cuban press", "exercise_type": "Rotación + press", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Rotación externa + press"},
    {"muscle": "Hombro", "name": "DB Y-raise", "exercise_type": "Elevación en Y", "pattern": "Mancuernas", "equipment": "Banco inclinado/de pie", "subtype": "Trapecio superior + deltoide"},
    {"muscle": "Hombro", "name": "DB W-raise", "exercise_type": "Elevación en W", "pattern": "Mancuernas", "equipment": "Banco inclinado", "subtype": "Manguito rotador + deltoide"},
    {"muscle": "Hombro", "name": "KB overhead press", "exercise_type": "Empuje vertical", "pattern": "Kettlebell", "equipment": "Libre", "subtype": "Center of mass distinto, estabilidad"},
    {"muscle": "Hombro", "name": "KB push press", "exercise_type": "Empuje vertical + pierna", "pattern": "Kettlebell", "equipment": "Libre", "subtype": "Explosivo"},
    {"muscle": "Hombro", "name": "KB bottom-up press", "exercise_type": "Empuje vertical", "pattern": "Kettlebell", "equipment": "Libre", "subtype": "GRAN estabilidad muñeca/hombro"},
    {"muscle": "Hombro", "name": "KB lateral raise", "exercise_type": "Abducción", "pattern": "Kettlebell", "equipment": "Libre", "subtype": "Similar a DB lateral"},
    {"muscle": "Hombro", "name": "KB front raise", "exercise_type": "Elevación frontal", "pattern": "Kettlebell", "equipment": "Libre", "subtype": "Deltoide anterior"},
    {"muscle": "Hombro", "name": "Band shoulder press", "exercise_type": "Empuje vertical", "pattern": "Banda", "equipment": "Bajo pies", "subtype": "Alternativa casera al press"},
    {"muscle": "Hombro", "name": "Band front raise", "exercise_type": "Elevación frontal", "pattern": "Banda", "equipment": "Bajo pies", "subtype": "Aislante anterior"},
    {"muscle": "Hombro", "name": "Band lateral raise", "exercise_type": "Abducción", "pattern": "Banda", "equipment": "Bajo pies", "subtype": "Aislante lateral"},
    {"muscle": "Hombro", "name": "Band pull-apart (altura hombro)", "exercise_type": "Abducción horizontal", "pattern": "Banda", "equipment": "De pie", "subtype": "Deltoide posterior + trapecio"},
    {"muscle": "Hombro", "name": "Band face pull", "exercise_type": "Tirón alto", "pattern": "Banda", "equipment": "Anclaje alto", "subtype": "Similar al cable face pull"},
    {"muscle": "Hombro", "name": "Cable shoulder press", "exercise_type": "Empuje vertical", "pattern": "Polea", "equipment": "Dos poleas bajas", "subtype": "Menos común pero viable"},
    {"muscle": "Hombro", "name": "Cable lateral raise (low pulley)", "exercise_type": "Abducción", "pattern": "Polea", "equipment": "Baja", "subtype": "Excelente tensión continua"},
    {"muscle": "Hombro", "name": "One-arm cable lateral raise", "exercise_type": "Abducción", "pattern": "Polea", "equipment": "Baja", "subtype": "Unilateral"},
    {"muscle": "Hombro", "name": "Cable front raise", "exercise_type": "Elevación frontal", "pattern": "Polea", "equipment": "Baja", "subtype": "Barra/cuerda"},
    {"muscle": "Hombro", "name": "High cable front raise", "exercise_type": "Elevación frontal", "pattern": "Polea", "equipment": "Alta", "subtype": "Desde alto hacia abajo"},
    {"muscle": "Hombro", "name": "Cable rear delt fly", "exercise_type": "Abducción horizontal", "pattern": "Polea", "equipment": "Media/alta", "subtype": "De pie, brazos cruzados"},
    {"muscle": "Hombro", "name": "Face pull (cable)", "exercise_type": "Tirón alto", "pattern": "Polea", "equipment": "Alta", "subtype": "Deltoide posterior + trapecio"},
    {"muscle": "Hombro", "name": "Cable Y-raise", "exercise_type": "Elevación en Y", "pattern": "Polea", "equipment": "Alta", "subtype": "Similar a DB Y-raise"},
    {"muscle": "Hombro", "name": "Shoulder press machine", "exercise_type": "Empuje vertical", "pattern": "Máquina", "equipment": "Selectorizada", "subtype": "Press de hombro clásico"},
    {"muscle": "Hombro", "name": "Plate-loaded shoulder press", "exercise_type": "Empuje vertical", "pattern": "Máquina", "equipment": "Plate-loaded", "subtype": "Palancas independientes"},
    {"muscle": "Hombro", "name": "Lateral raise machine", "exercise_type": "Abducción", "pattern": "Máquina", "equipment": "Selectorizada", "subtype": "Deltoide lateral"},
    {"muscle": "Hombro", "name": "Reverse pec-deck machine", "exercise_type": "Abducción horizontal", "pattern": "Máquina", "equipment": "Reverse fly", "subtype": "Deltoide posterior"},
    
    # ==================== GLÚTEO ====================
    {"muscle": "Glúteo", "name": "Glute bridge", "exercise_type": "Extensión cadera", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Bilateral, pies apoyados, básico"},
    {"muscle": "Glúteo", "name": "Glute bridge feet elevated", "exercise_type": "Extensión cadera", "pattern": "Peso corporal", "equipment": "Talones en banco/step", "subtype": "Mayor ROM isquios/glúteo"},
    {"muscle": "Glúteo", "name": "Single-leg glute bridge", "exercise_type": "Extensión cadera", "pattern": "Peso corporal", "equipment": "Suelo, unilateral", "subtype": "Aísla un glúteo, muy usado en rehab"},
    {"muscle": "Glúteo", "name": "Hip thrust (BW)", "exercise_type": "Extensión cadera", "pattern": "Peso corporal", "equipment": "Espalda en banco", "subtype": "Versión sin carga externa"},
    {"muscle": "Glúteo", "name": "Single-leg hip thrust (BW)", "exercise_type": "Extensión cadera", "pattern": "Peso corporal", "equipment": "Espalda en banco", "subtype": "Unilateral, alta activación"},
    {"muscle": "Glúteo", "name": "Frog pump", "exercise_type": "Extensión cadera", "pattern": "Peso corporal", "equipment": "Suelo, plantas juntas", "subtype": "Cadera abducida y rotada, más glúteo"},
    {"muscle": "Glúteo", "name": "Marching hip thrust", "exercise_type": "Extensión cadera", "pattern": "Peso corporal", "equipment": "Espalda en banco", "subtype": "Alternas levantando una pierna (anti-rotación)"},
    {"muscle": "Glúteo", "name": "Reverse hyper (improvisado)", "exercise_type": "Extensión cadera", "pattern": "Peso corporal", "equipment": "Banco", "subtype": "Tumbado boca abajo, elevando piernas"},
    {"muscle": "Glúteo", "name": "Step-up (glúteo)", "exercise_type": "Dominante cadera/rodilla", "pattern": "Peso corporal", "equipment": "Banco/step", "subtype": "Subida a banco, énfasis según altura"},
    {"muscle": "Glúteo", "name": "Walking lunge (glúteo)", "exercise_type": "Dominante cadera/rodilla", "pattern": "Peso corporal", "equipment": "Sin carga", "subtype": "Paso largo = más glúteo"},
    {"muscle": "Glúteo", "name": "Rear lunge", "exercise_type": "Dominante cadera", "pattern": "Peso corporal", "equipment": "Sin carga", "subtype": "Desplazas pierna atrás, glúteo delantera"},
    {"muscle": "Glúteo", "name": "Curtsy lunge", "exercise_type": "Dominante cadera", "pattern": "Peso corporal", "equipment": "Sin carga", "subtype": "Paso cruzado atrás, glúteo medio"},
    {"muscle": "Glúteo", "name": "Barbell hip thrust", "exercise_type": "Extensión cadera", "pattern": "Barra", "equipment": "Espalda en banco", "subtype": "Rey del glúteo, muy alta activación"},
    {"muscle": "Glúteo", "name": "Barbell hip thrust (wide stance)", "exercise_type": "Extensión cadera", "pattern": "Barra", "equipment": "Espalda en banco", "subtype": "Pies más abiertos, más glúteo medio"},
    {"muscle": "Glúteo", "name": "Barbell hip thrust (feet elevated)", "exercise_type": "Extensión cadera", "pattern": "Barra", "equipment": "Talones en step", "subtype": "Mayor ROM"},
    {"muscle": "Glúteo", "name": "Single-leg barbell hip thrust", "exercise_type": "Extensión cadera", "pattern": "Barra", "equipment": "Unilateral", "subtype": "Avanzado, difícil de cargar"},
    {"muscle": "Glúteo", "name": "Barbell glute bridge", "exercise_type": "Extensión cadera", "pattern": "Barra", "equipment": "Espalda en suelo", "subtype": "Menos ROM que hip thrust"},
    {"muscle": "Glúteo", "name": "Barbell good morning", "exercise_type": "Bisagra cadera", "pattern": "Barra", "equipment": "Libre", "subtype": "Erectores + glúteo/isquios"},
    {"muscle": "Glúteo", "name": "Back squat (emphasis glute)", "exercise_type": "Sentadilla", "pattern": "Barra", "equipment": "High/low bar", "subtype": "Mayor énfasis glúteo con profundidad"},
    {"muscle": "Glúteo", "name": "Low-bar squat", "exercise_type": "Sentadilla", "pattern": "Barra", "equipment": "Posición baja", "subtype": "Más cadena posterior"},
    {"muscle": "Glúteo", "name": "Box squat (glúteo)", "exercise_type": "Sentadilla", "pattern": "Barra", "equipment": "Caja", "subtype": "Ayuda a sentarse atrás, más cadera"},
    {"muscle": "Glúteo", "name": "Barbell reverse lunge", "exercise_type": "Dominante cadera", "pattern": "Barra", "equipment": "Libre", "subtype": "Paso atrás, cadera cargada"},
    {"muscle": "Glúteo", "name": "Barbell walking lunge", "exercise_type": "Dominante cadera/rodilla", "pattern": "Barra", "equipment": "Libre", "subtype": "Grande trabajo glúteo por paso largo"},
    {"muscle": "Glúteo", "name": "Barbell step-up (glúteo)", "exercise_type": "Dominante cadera", "pattern": "Barra", "equipment": "Banco", "subtype": "Glúteo en pierna que sube"},
    {"muscle": "Glúteo", "name": "Romanian deadlift (glúteo)", "exercise_type": "Bisagra cadera", "pattern": "Barra", "equipment": "Libre", "subtype": "Gran glúteo + femoral"},
    {"muscle": "Glúteo", "name": "Sumo deadlift (glúteo)", "exercise_type": "Bisagra cadera", "pattern": "Barra", "equipment": "Libre", "subtype": "Base amplia, mucho glúteo/aductores"},
    {"muscle": "Glúteo", "name": "Dumbbell hip thrust", "exercise_type": "Extensión cadera", "pattern": "Mancuernas", "equipment": "Espalda en banco", "subtype": "Mancuerna sobre cadera"},
    {"muscle": "Glúteo", "name": "DB glute bridge", "exercise_type": "Extensión cadera", "pattern": "Mancuernas", "equipment": "Suelo", "subtype": "Glute bridge con peso"},
    {"muscle": "Glúteo", "name": "Single-leg DB glute bridge", "exercise_type": "Extensión cadera", "pattern": "Mancuernas", "equipment": "Unilateral", "subtype": "Mancuerna en cadera de pierna activa"},
    {"muscle": "Glúteo", "name": "DB walking lunge (glúteo)", "exercise_type": "Dominante cadera/rodilla", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Carga en manos"},
    {"muscle": "Glúteo", "name": "DB reverse lunge (glúteo)", "exercise_type": "Dominante cadera", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Paso hacia atrás"},
    {"muscle": "Glúteo", "name": "DB Bulgarian split squat (glúteo)", "exercise_type": "Dominante cadera", "pattern": "Mancuernas", "equipment": "Pie trasero elevado", "subtype": "Mucho glúteo de pierna delantera"},
    {"muscle": "Glúteo", "name": "DB step-up (glúteo)", "exercise_type": "Dominante cadera", "pattern": "Mancuernas", "equipment": "Banco", "subtype": "Similar a barbell step-up"},
    {"muscle": "Glúteo", "name": "DB Romanian deadlift (glúteo)", "exercise_type": "Bisagra cadera", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Misma mecánica RDL"},
    {"muscle": "Glúteo", "name": "DB curtsy lunge", "exercise_type": "Dominante cadera", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Paso cruzado, glúteo medio"},
    {"muscle": "Glúteo", "name": "KB swing (glúteo)", "exercise_type": "Bisagra cadera", "pattern": "Kettlebell", "equipment": "Libre", "subtype": "Potente para glúteo/isquios"},
    {"muscle": "Glúteo", "name": "KB Romanian deadlift", "exercise_type": "Bisagra cadera", "pattern": "Kettlebell", "equipment": "Libre", "subtype": "Similar a DB RDL"},
    {"muscle": "Glúteo", "name": "KB goblet squat (profundo)", "exercise_type": "Sentadilla", "pattern": "Kettlebell", "equipment": "Frontal", "subtype": "Profundidad = más glúteo"},
    {"muscle": "Glúteo", "name": "KB reverse lunge", "exercise_type": "Dominante cadera", "pattern": "Kettlebell", "equipment": "Libre", "subtype": "Carga en rack o a los lados"},
    {"muscle": "Glúteo", "name": "Cable pull-through", "exercise_type": "Extensión cadera", "pattern": "Polea", "equipment": "Baja, de espaldas", "subtype": "Bisagra glúteo-isquio con cable"},
    {"muscle": "Glúteo", "name": "Cable glute kickback", "exercise_type": "Extensión cadera", "pattern": "Polea", "equipment": "Tobillera", "subtype": "Extensión pierna atrás, glúteo máximo"},
    {"muscle": "Glúteo", "name": "Standing hip abduction (cable)", "exercise_type": "Abducción cadera", "pattern": "Polea", "equipment": "Tobillera lateral", "subtype": "Glúteo medio/min"},
    {"muscle": "Glúteo", "name": "Band hip thrust", "exercise_type": "Extensión cadera", "pattern": "Banda", "equipment": "Sobre cadera", "subtype": "Banded hip thrust en banco/suelo"},
    {"muscle": "Glúteo", "name": "Band glute bridge", "exercise_type": "Extensión cadera", "pattern": "Banda", "equipment": "Sobre cadera", "subtype": "Versión con banda"},
    {"muscle": "Glúteo", "name": "Banded abduction (sentado)", "exercise_type": "Abducción cadera", "pattern": "Banda", "equipment": "Alrededor de rodillas", "subtype": "Sentado abriento rodillas"},
    {"muscle": "Glúteo", "name": "Banded monster walk", "exercise_type": "Abducción/estabilidad", "pattern": "Banda", "equipment": "A la altura de rodillas/tobillos", "subtype": "Caminatas laterales/diagonales"},
    {"muscle": "Glúteo", "name": "Banded side step", "exercise_type": "Abducción", "pattern": "Banda", "equipment": "A la altura de rodillas", "subtype": "Pasos laterales"},
    {"muscle": "Glúteo", "name": "Hip thrust machine", "exercise_type": "Extensión cadera", "pattern": "Máquina", "equipment": "Hip thrust machine", "subtype": "Versión guiada con apoyo de hombros"},
    {"muscle": "Glúteo", "name": "Machine glute bridge", "exercise_type": "Extensión cadera", "pattern": "Máquina", "equipment": "Selectorizada", "subtype": "Similar a hip thrust guiado"},
    {"muscle": "Glúteo", "name": "Machine glute kickback", "exercise_type": "Extensión cadera", "pattern": "Máquina", "equipment": "Kickback machine", "subtype": "Empujas plataforma hacia atrás"},
    {"muscle": "Glúteo", "name": "45° hip extension (glute focus)", "exercise_type": "Extensión cadera", "pattern": "Máquina/banco", "equipment": "Banco 45°", "subtype": "Foco glúteo ajustando torso/pies"},
    {"muscle": "Glúteo", "name": "Reverse hyper machine", "exercise_type": "Extensión cadera", "pattern": "Máquina", "equipment": "Reverse hyper", "subtype": "Glúteo máximo + lumbar"},
    {"muscle": "Glúteo", "name": "Leg press (feet high & wide)", "exercise_type": "Dominante cadera", "pattern": "Máquina", "equipment": "Prensa", "subtype": "Pies altos/abiertos = más glúteo"},
    {"muscle": "Glúteo", "name": "Hip abduction machine", "exercise_type": "Abducción cadera", "pattern": "Máquina", "equipment": "Selectorizada", "subtype": "Glúteo medio principalmente"},
    
    # ==================== ISQUIOTIBIALES ====================
    {"muscle": "Isquiotibiales", "name": "Romanian deadlift", "exercise_type": "Bisagra", "pattern": "Barra", "equipment": "Libre", "subtype": "Foco isquios/glúteo y erectores"},
    {"muscle": "Isquiotibiales", "name": "Stiff-leg deadlift", "exercise_type": "Bisagra", "pattern": "Barra", "equipment": "Libre", "subtype": "Piernas casi rectas, más isquios"},
    {"muscle": "Isquiotibiales", "name": "Lying leg curl machine", "exercise_type": "Flexión rodilla", "pattern": "Máquina", "equipment": "Tumbado", "subtype": "Aislante clásico de isquios"},
    {"muscle": "Isquiotibiales", "name": "Seated leg curl machine", "exercise_type": "Flexión rodilla", "pattern": "Máquina", "equipment": "Sentado", "subtype": "Isquios en posición estirada"},
    {"muscle": "Isquiotibiales", "name": "DB Romanian deadlift", "exercise_type": "Bisagra", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Variante unilateral o bilateral"},
    {"muscle": "Isquiotibiales", "name": "Nordic hamstring curl", "exercise_type": "Flexión rodilla excéntrica", "pattern": "Peso corporal", "equipment": "Rodillas en el suelo, pies fijados", "subtype": "Excéntrico muy potente, prevención lesiones"},
    {"muscle": "Isquiotibiales", "name": "Good morning", "exercise_type": "Bisagra cadera", "pattern": "Barra", "equipment": "Libre", "subtype": "Foco isquios/glúteo con torso inclinado"},
    {"muscle": "Isquiotibiales", "name": "Glute-ham raise (GHR)", "exercise_type": "Flexión rodilla + ext. cadera", "pattern": "Máquina", "equipment": "GHR apparatus", "subtype": "Muy demandante, excéntrico fuerte"},
    {"muscle": "Isquiotibiales", "name": "Single-leg RDL", "exercise_type": "Bisagra cadera", "pattern": "Mancuernas", "equipment": "Libre", "subtype": "Control y estabilidad altos"},
    {"muscle": "Isquiotibiales", "name": "Standing leg curl machine", "exercise_type": "Flexión rodilla", "pattern": "Máquina", "equipment": "De pie, unilateral", "subtype": "Aísla cada pierna"},
    
    # ==================== PANTORRILLA ====================
    {"muscle": "Pantorrilla", "name": "Standing calf raise (machine)", "exercise_type": "Flexión plantar", "pattern": "Máquina", "equipment": "Selectorizada", "subtype": "Rodillas extendidas, gastrocnemios"},
    {"muscle": "Pantorrilla", "name": "Seated calf raise machine", "exercise_type": "Flexión plantar", "pattern": "Máquina", "equipment": "Sentado", "subtype": "Rodilla flexionada, más sóleo"},
    {"muscle": "Pantorrilla", "name": "Leg press calf raise", "exercise_type": "Flexión plantar", "pattern": "Máquina", "equipment": "Leg press", "subtype": "Usando la prensa para gemelos"},
    {"muscle": "Pantorrilla", "name": "Standing calf raise (BW)", "exercise_type": "Flexión plantar", "pattern": "Peso corporal", "equipment": "Step", "subtype": "Versión sin carga"},
    {"muscle": "Pantorrilla", "name": "Single-leg calf raise", "exercise_type": "Flexión plantar", "pattern": "Peso corporal", "equipment": "Step", "subtype": "Unilateral para más carga"},
    {"muscle": "Pantorrilla", "name": "Donkey calf raise", "exercise_type": "Flexión plantar", "pattern": "Máquina/peso", "equipment": "Banco", "subtype": "Torso inclinado, gran estiramiento"},
    
    # ==================== ABDOMEN ====================
    {"muscle": "Abdomen", "name": "Crunch", "exercise_type": "Flexión tronco", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Recto abdominal superior"},
    {"muscle": "Abdomen", "name": "Plank", "exercise_type": "Anti-extensión", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Plancha frontal clásica"},
    {"muscle": "Abdomen", "name": "Hanging leg raise", "exercise_type": "Elevación cadera", "pattern": "Peso corporal", "equipment": "Barra", "subtype": "Piernas rectas, muy demandante"},
    {"muscle": "Abdomen", "name": "Russian twist", "exercise_type": "Rotación", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Oblicuos"},
    {"muscle": "Abdomen", "name": "Cable crunch (kneeling)", "exercise_type": "Flexión tronco", "pattern": "Polea", "equipment": "Polea alta, cuerda", "subtype": "Muy popular para recto"},
    {"muscle": "Abdomen", "name": "Ab wheel rollout", "exercise_type": "Anti-extensión", "pattern": "Peso corporal", "equipment": "Rueda/barra", "subtype": "Muy exigente para core"},
    {"muscle": "Abdomen", "name": "Side plank", "exercise_type": "Anti-flexión lateral", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Oblicuos/transverso"},
    {"muscle": "Abdomen", "name": "Bicycle crunch", "exercise_type": "Flexión + rotación", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Recto y oblicuos"},
    {"muscle": "Abdomen", "name": "V-up / Jackknife", "exercise_type": "Flexión global", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Brazos y piernas se encuentran"},
    {"muscle": "Abdomen", "name": "Hollow body hold", "exercise_type": "Anti-extensión", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Transverso + recto"},
    {"muscle": "Abdomen", "name": "Dead bug", "exercise_type": "Anti-extensión", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Patrón contralateral controlado"},
    {"muscle": "Abdomen", "name": "Reverse crunch", "exercise_type": "Flexión cadera", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Parte inferior del recto"},
    {"muscle": "Abdomen", "name": "Mountain climber", "exercise_type": "Dinámico", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Core + cardio"},
    {"muscle": "Abdomen", "name": "Hanging knee raise", "exercise_type": "Elevación cadera", "pattern": "Peso corporal", "equipment": "Barra", "subtype": "Rodillas al pecho colgado"},
    {"muscle": "Abdomen", "name": "Toes-to-bar", "exercise_type": "Elevación cadera completa", "pattern": "Peso corporal", "equipment": "Barra", "subtype": "Pies a la barra; avanzado"},
    {"muscle": "Abdomen", "name": "Dragon flag", "exercise_type": "Anti-extensión extrema", "pattern": "Peso corporal", "equipment": "Banco", "subtype": "Nivel muy alto"},
    {"muscle": "Abdomen", "name": "Pallof press", "exercise_type": "Anti-rotación", "pattern": "Polea/banda", "equipment": "Altura pecho", "subtype": "Resistir giro al extender brazos"},
    {"muscle": "Abdomen", "name": "Woodchopper high-to-low", "exercise_type": "Rotación diagonal", "pattern": "Polea", "equipment": "Alta → baja", "subtype": "Oblicuos/transverso"},
    {"muscle": "Abdomen", "name": "Woodchopper low-to-high", "exercise_type": "Rotación diagonal", "pattern": "Polea", "equipment": "Baja → alta", "subtype": "Variante opuesta"},
    {"muscle": "Abdomen", "name": "Weighted plank", "exercise_type": "Anti-extensión", "pattern": "Peso adicional", "equipment": "Placa en espalda", "subtype": "Aumenta demanda sin cambiar forma"},
    {"muscle": "Abdomen", "name": "Landmine rotation", "exercise_type": "Rotación", "pattern": "Barra + landmine", "equipment": "De pie", "subtype": "Girando barra en arco"},
    {"muscle": "Abdomen", "name": "Sit-up", "exercise_type": "Flexión tronco", "pattern": "Peso corporal", "equipment": "Suelo", "subtype": "Más cadera/iliopsoas"},
    {"muscle": "Abdomen", "name": "Machine crunch", "exercise_type": "Flexión tronco", "pattern": "Máquina", "equipment": "Crunch machine", "subtype": "Empuje con tronco contra resistencia"},
    {"muscle": "Abdomen", "name": "Captain's chair leg raise", "exercise_type": "Elevación cadera", "pattern": "Máquina", "equipment": "Silla romana", "subtype": "Rodillas/piernas al frente"},
    
    # ==================== ANTEBRAZO ====================
    {"muscle": "Antebrazo", "name": "Barbell wrist curl", "exercise_type": "Flexión muñeca", "pattern": "Barra", "equipment": "Libre", "subtype": "Palma hacia arriba, flexores"},
    {"muscle": "Antebrazo", "name": "Barbell reverse wrist curl", "exercise_type": "Extensión muñeca", "pattern": "Barra", "equipment": "Libre", "subtype": "Palmas abajo, extensores"},
    {"muscle": "Antebrazo", "name": "Dumbbell wrist curl", "exercise_type": "Flexión muñeca", "pattern": "Mancuernas", "equipment": "Antebrazo apoyado", "subtype": "Similar a barra, unilateral"},
    {"muscle": "Antebrazo", "name": "Dumbbell reverse wrist curl", "exercise_type": "Extensión muñeca", "pattern": "Mancuernas", "equipment": "Antebrazo apoyado", "subtype": "Extensores antebrazo"},
    {"muscle": "Antebrazo", "name": "Farmer's walk", "exercise_type": "Soporte/agarre", "pattern": "Mancuernas", "equipment": "Caminar", "subtype": "Gran estímulo de agarre"},
    {"muscle": "Antebrazo", "name": "Dead hang", "exercise_type": "Soporte/agarre", "pattern": "Peso corporal", "equipment": "Barra fija", "subtype": "Colgarse pasivo, flexores de dedos/antebrazo"},
    {"muscle": "Antebrazo", "name": "Plate pinch hold", "exercise_type": "Pinza", "pattern": "Discos", "equipment": "Discos lisos", "subtype": "Pellizcar discos con dedos"},
    {"muscle": "Antebrazo", "name": "Wrist roller", "exercise_type": "Flex/Ext muñeca", "pattern": "Barra/cilindro", "equipment": "Wrist roller", "subtype": "Se enrolla y desenrolla peso"},
    {"muscle": "Antebrazo", "name": "Reverse curl", "exercise_type": "Flexión codo prono", "pattern": "Barra", "equipment": "Libre", "subtype": "Brachiorradial + extensores"},
    {"muscle": "Antebrazo", "name": "Grippers", "exercise_type": "Cierre pinza", "pattern": "Gripper", "equipment": "Mecánico", "subtype": "Cerrar y mantener, fuerza de agarre"},
]

# Define achievements
ACHIEVEMENTS_DATA = [
    {"code": "FIRST_WORKOUT", "name": "Primeros Pasos", "description": "Completa tu primer entrenamiento", "category": "MILESTONE", "points": 10, "rarity": "COMMON", "criteria": {"workouts_completed": 1}},
    {"code": "WEEK_WARRIOR", "name": "Guerrero Semanal", "description": "Entrena 7 días seguidos", "category": "STREAK", "points": 50, "rarity": "RARE", "criteria": {"streak_days": 7}},
    {"code": "MONTH_MASTER", "name": "Maestro Mensual", "description": "Entrena 30 días seguidos", "category": "STREAK", "points": 200, "rarity": "EPIC", "criteria": {"streak_days": 30}},
    {"code": "CENTURY_CLUB", "name": "Club del Siglo", "description": "Levanta 100kg en una sesión", "category": "VOLUME", "points": 100, "rarity": "RARE", "criteria": {"session_volume": 100}},
    {"code": "TONNAGE_TITAN", "name": "Titán del Tonelaje", "description": "Acumula 10,000kg de volumen total", "category": "VOLUME", "points": 500, "rarity": "LEGENDARY", "criteria": {"total_volume": 10000}},
    {"code": "PR_HUNTER", "name": "Cazador de PRs", "description": "Logra 10 PRs diferentes", "category": "PR", "points": 150, "rarity": "EPIC", "criteria": {"total_prs": 10}},
    {"code": "CONSISTENCY_KING", "name": "Rey de la Consistencia", "description": "No faltes a un entrenamiento programado por 4 semanas", "category": "CONSISTENCY", "points": 100, "rarity": "RARE", "criteria": {"weeks_consistent": 4}},
    {"code": "TEN_WORKOUTS", "name": "En Marcha", "description": "Completa 10 entrenamientos", "category": "MILESTONE", "points": 25, "rarity": "COMMON", "criteria": {"workouts_completed": 10}},
    {"code": "FIFTY_WORKOUTS", "name": "Dedicado", "description": "Completa 50 entrenamientos", "category": "MILESTONE", "points": 100, "rarity": "RARE", "criteria": {"workouts_completed": 50}},
    {"code": "HUNDRED_WORKOUTS", "name": "Centenario", "description": "Completa 100 entrenamientos", "category": "MILESTONE", "points": 250, "rarity": "EPIC", "criteria": {"workouts_completed": 100}},
    {"code": "FIRST_PR", "name": "Primer Récord", "description": "Logra tu primer PR", "category": "PR", "points": 20, "rarity": "COMMON", "criteria": {"total_prs": 1}},
    {"code": "BEGINNER_LEVEL", "name": "Nivel Principiante", "description": "Alcanza el nivel Beginner", "category": "MILESTONE", "points": 50, "rarity": "COMMON", "criteria": {"account_level": "Beginner"}},
    {"code": "INTERMEDIATE_LEVEL", "name": "Nivel Intermedio", "description": "Alcanza el nivel Intermediate", "category": "MILESTONE", "points": 150, "rarity": "RARE", "criteria": {"account_level": "Intermediate"}},
    {"code": "ADVANCED_LEVEL", "name": "Nivel Avanzado", "description": "Alcanza el nivel Advanced", "category": "MILESTONE", "points": 300, "rarity": "EPIC", "criteria": {"account_level": "Advanced"}},
    {"code": "ELITE_LEVEL", "name": "Nivel Elite", "description": "Alcanza el nivel Elite", "category": "MILESTONE", "points": 500, "rarity": "LEGENDARY", "criteria": {"account_level": "Elite"}},
    {"code": "EARLY_BIRD", "name": "Madrugador", "description": "Completa un entrenamiento antes de las 7am", "category": "CONSISTENCY", "points": 30, "rarity": "COMMON", "criteria": {"early_workout": True}},
    {"code": "NIGHT_OWL", "name": "Búho Nocturno", "description": "Completa un entrenamiento después de las 10pm", "category": "CONSISTENCY", "points": 30, "rarity": "COMMON", "criteria": {"late_workout": True}},
    {"code": "VARIETY_PACK", "name": "Variedad", "description": "Usa 20 ejercicios diferentes", "category": "MILESTONE", "points": 75, "rarity": "RARE", "criteria": {"unique_exercises": 20}},
    {"code": "MUSCLE_MASTER", "name": "Maestro Muscular", "description": "Entrena todos los grupos musculares en una semana", "category": "CONSISTENCY", "points": 60, "rarity": "RARE", "criteria": {"all_muscles_week": True}},
    {"code": "THOUSAND_REPS", "name": "Mil Repeticiones", "description": "Acumula 1,000 repeticiones totales", "category": "VOLUME", "points": 100, "rarity": "RARE", "criteria": {"total_reps": 1000}},
]
